### ISSUE TITLE
'triangle' sample gives GPU Error at current state

### ISSUE THREAD

**Issue by jthecodebuilder** [XboxDev/nxdk#41] opened 2018-04-30 21:05 UTC
I don't know anything about programming the Xbox's GPU at the moment, but here is the error I am getting when running the output default.xbe:
(Keep in mind I had to hand copy this by hand as I do not have the proper means for debug log copy and paste here.)
```
GPU Error : object state invalid error!
Error binary flags : 08x
Channel ID : 2048 (0=3D)
Channel class : 0
Push buffer inner register target : 04x
Push buffer data (lo) or instance : 08x
Push buffer data (hi) or instance : 08x
Multi-purpose register A [0x1D8C] : 08x
Multi-purpose register A [0x1D90] : 08x

Report is accurate only if pb_trace_mode=1 (slower)
System halted
```
Not sure how to enable pb_trace_mode=1 though...

**Comment by jthecodebuilder** [comment] 2018-04-30 22:34
On a real Xbox, revision v1.0.

**Comment by thrimbor** [comment] 2019-02-18 18:20
I tried to dig into this a bit in the last few hours.

First of all, this sample seems to run fine on a debug BIOS loaded via PBL, but it crashes on the retail BIOS of my 1.0 PAL Xbox.

When using #85 to improve debug output and `#define DBG` to set `pb_trace_mode=1`, this comes out:
![img](https://user-images.githubusercontent.com/1339483/52969317-30f2f400-33b0-11e9-965e-7afc0821a040.jpg)

The error is triggered by `draw_arrays()`:
```
/* Send draw commands for the triangles */
static void draw_arrays(unsigned int mode, int start, int count)
{
    uint32_t *p = pb_begin();
    pb_push1(p, NV097_SET_BEGIN_END, mode); p += 2;

    pb_push(p++,0x40000000|NV097_DRAW_ARRAYS,1); //bit 30 means all params go to same register 0x1810
    *(p++) = MASK(NV097_DRAW_ARRAYS_COUNT, (count-1)) | MASK(NV097_DRAW_ARRAYS_START_INDEX, start);

    pb_push1(p,NV097_SET_BEGIN_END, NV097_SET_BEGIN_END_OP_END); p += 2;
    pb_end(p);
}
```

The register that the error message mentions (0x1810) is NV097_DRAW_ARRAYS, the following `pb_push1()` seems to trigger the error. p = 2213917156 and pb_PushNext = 2213917148 when the error message is generated.

I tried to fix this myself, but my knowledge of this stuff isn't very advanced yet. I'm willing to test stuff though should someone have an idea on how to fix this.

**Comment by JayFoxRox** [comment] 2019-05-30 19:21
This post contains some observations about the discussion and the triangle / pbkit code in general; I did not reproduce or investigate this issue - I just accidentally found some stuff which might be relevant.

---

The `DBG` error is because `pb_push` is a macro which is not updating the internal state; so you can't mix it with `pb_push1` which checks this. So once you used `pb_push` you can't use `pb_push#` anymore, until you `pb_end`. Using `pb_push#` before `pb_push` is not an issue.

An ugly workaround for the triangle sample would be this, to avoid mixing:

```c
pb_push(p++, NV097_SET_BEGIN_END, 1); *p++ = NV097_SET_BEGIN_END_OP_END;
pb_end(p);
```

It's a bug in pbkit. `pb_push` shouldn't be a macro - and it should update the internal state (and do some other sanity checks).

Once this is addressed you can debug again.

---

One thing I was wondering about was the potential effect on memory layout. I noticed that the `triangle` code does something like:

```c
/* Set vertex position attribute */
set_attrib_pointer(0, NV097_SET_VERTEX_DATA_ARRAY_FORMAT_TYPE_F,
                   3, sizeof(ColoredVertex), &alloc_vertices[0]);
```

Where `alloc_vertices` comes from `MmAllocateContiguousMemoryEx`; my understanding is that this is a virtual address that's not necessarily identity mapped? I believe the GPU has no page-tables configured, so this should probably be wrapped in `MmGetPhysicalAddress` to make sure that the address is a physical one (which should only be done once, to avoid overhead).

**Comment by thrimbor** [comment] 2019-05-30 22:12
I tested both changes without success. The `pb_push`-change gets rid of the warning (`pb_PushIndex+=2; pb_PushNext += 2;` before `pb_push1` seems to have the same effect), but even with `MmAllocateContiguousMemoryEx`, the actual error remains (although I wonder how it works in xqemu without it).

**Comment by JayFoxRox** [comment] 2020-01-05 08:13
Should be fixed by https://github.com/JayFoxRox/nxdk/pull/64; I'll probably upstream this soon (after a cleanup where I'll have to figure out which parts are necessary or missing).

I assume that the critical register is the one that sets texture shaders.

Some dashboards leaves texture 0 enabled and the texture shader happens to match that.
Other dashboards have texture 0 disabled, but the texture shader appears to use the texture - this is invalid.

The mesh sample works around this as it explicitly sets up textures + it also has a texture shader.

To fix this, pbkit should set safe defaults, as done in the code linked above - there are a handful of registers affected by this.

**Closed** 2020-01-15 14:01 UTC
