### ISSUE TITLE
༼ つ ◕_◕ ༽つ GIVE BUILDS ༼ つ ◕_◕ ༽つ

### ISSUE THREAD

**Issue by adamc295** [XboxDev/nxdk#43] opened 2018-07-17 17:45 UTC

**Comment by DarkGabbz** [comment] 2018-07-17 17:50
![grafik](https://user-images.githubusercontent.com/21977338/42836185-99dfdce0-89fa-11e8-97e8-dc7c507cfa3b.png)

**Comment by JayFoxRox** [comment] 2018-07-17 17:53
Implied duplicate of #36.

This is also a serious project about developing a toolchain, not a meme.
*(Because it attracts the wrong kind of people, as evidenced by the immediate response)*

Also, quite frankly, there isn't much we can provide here. You'll need LLVM which is packaged differently for different platforms.
We could only provide our dependencies at best.

Furthermore, this is a toolchain for an embedded platform - this suggests you can already code.
If you can't code, you probably shouldn't be using it.
Setting up nxdk is moderately simple and can be done in a matter of minutes, even by beginners.

If you have issues setting up nxdk, please create a new *more serious* issue.

Locked and closed.

**Closed by JayFoxRox** 2018-07-17 17:53 UTC
