### ISSUE TITLE
lib.exe where?

### ISSUE THREAD

**Issue by jthecodebuilder** [XboxDev/nxdk#38] opened 2018-04-29 06:21 UTC
**unable to find lib.exe in PATH: : No such file or directory** happens on everything I try to compile, and I am super confused and frustrated that this issue seems **very**  unique in my case.

I am running Windows 10 x64 with MSYS2 32bit.

**Comment by JayFoxRox** [comment] 2018-04-29 09:15
* How did you install nxdk?
* At which step does this happen?
* Do you have a full log?

**Comment by jthecodebuilder** [comment] 2018-04-29 09:52
- I installed/downloaded it by the preferred method in the **README.md**
- It appears to be happening at **`[ LD       ] main.exe`**
- And I do have a full log (atleast to the best of my abilities), preferrably using the '**hello**' example as a baseline to see what's going wrong
```
$ make
[ DEP      ] /home/gmodk_000/nxdk/samples/hello/main.c.d
[ CC       ] /home/gmodk_000/nxdk/samples/hello/main.obj
[ LD       ] main.exe
unable to find lib.exe in PATH: : No such file or directory
make: *** [/home/gmodk_000/nxdk/samples/hello/../../Makefile:96: main.exe] Error 1
```

**Comment by JayFoxRox** [comment] 2018-04-29 11:56
I'm able to reproduce the issue but I couldn't find a solution yet.

I'd assume that this is a bug in the msys "lld".
I've asked about this in the MSYS2 IRC channel but haven't got a reponse yet.

---

As an alternative, the wiki also has installation instructions for WSL.
However, I'm not sure how many people tried that either. Fixes are welcome.

*(I also think we should move the existing documentation from the README to the wiki, so it can be updated more easily by users)*

**Comment by jthecodebuilder** [comment] 2018-04-30 02:56
Is the triangle sample supposed to give a GPU Error, though?

**Comment by thrimbor** [comment] 2018-04-30 04:56
@jthecodebuilder Afaik WSL should provide access to Windows drives in /mnt.

**Comment by jthecodebuilder** [comment] 2018-04-30 06:01
I know that already, I was just not sure if it would convert to the Windows filesystem until I tried.

**Comment by elieux** [comment] 2018-04-30 10:46
Could you post the test case, so I can try it locally?

**Comment by JayFoxRox** [comment] 2018-04-30 11:12
@jthecodebuilder The wiki should be editable by everyone, please fix the broken documentation yourself. The maintainers can't do such things because we don't run all supported platforms ourselves.

Also, yes, 0ldskoo1 is actually a capture-the-flag challenge so the red box is supposed to hide the actual message. I do agree that it should be modified for the nxdk release because people have repeatedly been confused by this.

I'm not aware about a GPU error on the triangle sample. Please create a new issue if you think this might be a bug.

**Comment by JayFoxRox** [comment] 2018-08-16 11:26
Looks like the wiki has been updated. I'm closing this issue - please inform us if the problem persists.

**Closed by JayFoxRox** 2018-08-16 11:26 UTC

**Comment by JayFoxRox** [comment] 2018-09-11 13:35
Reading over this again, I'm not sure why I closed this. WSL seems to be a workaround, but MSYS2 is still broken?

If anyone runs into this issue with MSYS again, please create a new issue and also link to this one.
