### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [XboxDev/nxdk#522] opened 2021-12-06 19:25 UTC
Hey y’all, so I just copied the example makefile on the GitHub tutorial changed some things here and there and then I tried to compile the makefile but then a error popped up and it says, make *** No targets. Stop. Idk what this means so can you help me with the error please!

**Comment by kosmas12** [comment] 2021-12-06 19:27
Good day!

Would you mind making sure that the NXDK_DIR is set correctly in your Makefile and that you're in the corect directory?

Ideally, if these are correct, it'd be nice if you could send the output of `make -v` so we can see the entire build log and figure out the issue.

Thanks!

**Comment by NeoGeoFreak2004** [comment] 2021-12-06 19:34
Crap, I forgot the include $(NXDK_DIR)/Makefile so do I need that compiler flag to make the program?

**Comment by kosmas12** [comment] 2021-12-06 19:35
Yes, this is required, as this is the only way to pull the nxdk Makefile into your project and bring all the compile targets etc. to scope so that `make` can do its job.

**Comment by dracc** [comment] 2021-12-07 04:15
Duplicate of #519. Please stop spamming the issue tracker.

**Closed** 2021-12-14 09:17 UTC
