### ISSUE TITLE
Samples don't work in CXBX-Reloaded

### ISSUE THREAD

**Issue by lorecast162** [XboxDev/nxdk#352] opened 2020-05-24 22:52 UTC
I tried to compile the `hello` and `sdl` samples and neither works.
I'm trying to load the .xbe in Cxbx-Reloaded and both stop with a black screen as soon as I run either of them
[This file is the Kernel output I get from hello](https://github.com/XboxDev/nxdk/files/4674564/KrnlDebug.txt)
[This is the Kernel output from sdl](https://github.com/XboxDev/nxdk/files/4674566/KrnlDebug.txt)
They both look pretty much identical to me.
Maybe this is some form of incompatibility?
I also saw that dumping xbe info revealed that all of them apparently had invalid signatures. Should I be worried or is it normal? I'm completely new to programming for the xbox

**Comment by GXTX** [comment] 2020-05-24 22:58
This is a known issue with CXBX-R, the applications should be running in the background however there is no video. This is not an issue with NXDK but rather the way CXBX-R handles symbol detection. You can confirm this by using `OutputDebugString()` and you should see some console output. Try using either a real Xbox or XQEMU to test.

**Comment by JayFoxRox** [comment] 2020-05-24 23:37
> I'm trying to load the .xbe in Cxbx-Reloaded and both stop with a black screen as soon as I run either of them

Yes. This is expected.

This is not a problem with nxdk, but with Cxbx-R.

While Cxbx-R is advertised as an "Xbox emulator" it's actually an "XDK API emulator".
Cxbx-R has very limited support for emulating Xbox *hardware* (via LLE); it only supports XDK APIs (via UHLE) and xboxkrnl.exe (via HLE).

nxdk does *not* use XDK APIs (and underlying drivers) and implements its own drivers (as the XDK drivers are proprietary and copyrighted by Microsoft).

So Cxbx-R will fail to recognize any functions.

You can still make homebrew in nxdk that works in Cxbx-R, but it can not use any Xbox specific hardware (or very limited use of it), and it will be restricted to the functions provided by xboxkrnl.exe (as this is also emulated by Cxbx-R).

XQEMU and MAME are Xbox *hardware* emulators (via LLE; exclusively) and won't have problems with nxdk homebrew (although some hardware features aren't emulated).

>  I also saw that dumping xbe info revealed that all of them apparently had invalid signatures. Should I be worried or is it normal? I'm completely new to programming for the xbox

This is expected.

The signature would verify that it's a licensed MS product. As we can not "sign" our XBEs (because we don't have Microsofts private key to do this) the signature checks will fail.
[See more information at wikipedia](https://en.wikipedia.org/wiki/Code_signing).

If you try to load an unsigned XBE on an unmodified Xbox, it will refuse to start it.
So running an nxdk binary requires a hacked Xbox to run homebrew (typically a softmod or patched kernel on modchip).
This also applies to emulators like XQEMU or MAME: You must patch the kernel that runs on your virtual Xbox or homebrew won't work (in fact, neither of those emulators emulates DVD-drive security, so you even need a patched kernel to run most signed games).

---

If you need more help or guidance for nxdk, I'd suggest to reach out via Discord: https://github.com/XboxDev/XboxDev

I'll close this issue and mark it as invalid, because it's not an issue with nxdk. I wouldn't even call it an issue with Cxbx-R: it's just something that Cxbx-R wasn't designed for (the original Cxbx/Cxbe was designed to handle OpenXDK, but the concept was also quickly given up on).

**Closed by JayFoxRox** 2020-05-24 23:37 UTC

**Comment by lorecast162** [comment] 2020-05-26 12:04
> > I'm trying to load the .xbe in Cxbx-Reloaded and both stop with a black screen as soon as I run either of them
> 
> Yes. This is expected.
> 
> This is not a problem with nxdk, but with Cxbx-R.
> 
> While Cxbx-R is advertised as an "Xbox emulator" it's actually an "XDK API emulator".
> Cxbx-R has very limited support for emulating Xbox _hardware_ (via LLE); it only supports XDK APIs (via UHLE) and xboxkrnl.exe (via HLE).
> 
> nxdk does _not_ use XDK APIs (and underlying drivers) and implements its own drivers (as the XDK drivers are proprietary and copyrighted by Microsoft).
> 
> So Cxbx-R will fail to recognize any functions.
> 
> You can still make homebrew in nxdk that works in Cxbx-R, but it can not use any Xbox specific hardware (or very limited use of it), and it will be restricted to the functions provided by xboxkrnl.exe (as this is also emulated by Cxbx-R).
> 
> XQEMU and MAME are Xbox _hardware_ emulators (via LLE; exclusively) and won't have problems with nxdk homebrew (although some hardware features aren't emulated).
> 
> > I also saw that dumping xbe info revealed that all of them apparently had invalid signatures. Should I be worried or is it normal? I'm completely new to programming for the xbox
> 
> This is expected.
> 
> The signature would verify that it's a licensed MS product. As we can not "sign" our XBEs (because we don't have Microsofts private key to do this) the signature checks will fail.
> [See more information at wikipedia](https://en.wikipedia.org/wiki/Code_signing#Unsigned_code_in_gaming_and_consumer_devices).
> 
> If you try to load an unsigned XBE on an unmodified Xbox, it will refuse to start it.
> So running an nxdk binary requires a hacked Xbox to run homebrew (typically a softmod or patched kernel on modchip).
> This also applies to emulators like XQEMU or MAME: You must patch the kernel that runs on your virtual Xbox or homebrew won't work (in fact, neither of those emulators emulates DVD-drive security, so you even need a patched kernel to run most signed games).
> 
> If you need more help or guidance for nxdk, I'd suggest to reach out via Discord: https://github.com/XboxDev/XboxDev
> 
> I'll close this issue and mark it as invalid, because it's not an issue with nxdk. I wouldn't even call it an issue with Cxbx-R: it's just something that Cxbx-R wasn't designed for (the original Cxbx/Cxbe was designed to handle OpenXDK, but the concept was also quickly given up on).

Thanks a lot for clarifying
