### ISSUE TITLE
sdl_ttf sample

### ISSUE THREAD

**Issue by mystyq** [XboxDev/nxdk#653] opened 2023-07-25 19:20 UTC
```TTF_RenderText_Blended(font, "xbox", font_color);``` does not render text.
```TTF_RenderText_Blended(font, "xbox\00", font_color);``` renders text.

It seems ```xbox``` isn't accepted for some reason.  Why?

**Comment by thrimbor** [comment] 2023-07-25 19:41
I can't reproduce that. Swapping `nxdk` for `xbox` in the sample works just fine.

**Comment by mystyq** [comment] 2023-07-25 20:01
My apologies, I should have mentioned I am using another font.  The supplied ```vegur-regular.ttf``` does render the text.  I am using ```https://www.fontspace.com/xbox-original-font-f53702```.  Could this be an issue with the font itself?

**Comment by thrimbor** [comment] 2023-07-25 22:28
That font also works just fine for me: 
![image](https://github.com/XboxDev/nxdk/assets/1339483/4e1cad22-9b18-46c0-868f-034a29b2d818)

**Comment by mystyq** [comment] 2023-07-25 22:52
Strange.  

```
  const char* font_path = "D:\\xbox.ttf";
  const int font_size = 96;
  font = TTF_OpenFont(font_path, font_size);
  if (font == NULL) {
    debugPrint("Couldn't load font: %s", TTF_GetError());
    Sleep(2000);
    goto cleanup;
  }
								              //#76BF05
  SDL_Color font_color = {0x76, 0xBF, 0x05, 0xFF};
  surface = TTF_RenderText_Blended(font, "xbox", font_color);
  TTF_CloseFont(font);
  if (surface == NULL) {
    debugPrint("TTF_RenderText failed: %s", TTF_GetError());
    Sleep(2000);
    goto cleanup;
  }
```

This is what I get after loading the .iso into XEMU on W11 machine:

<img width="479" alt="image" src="https://github.com/XboxDev/nxdk/assets/26229904/fe9e74cf-6876-428b-bd73-6c32516edca9">

I've also tested it on real hardware with the same behavior.

**Comment by mystyq** [comment] 2023-07-26 14:04
Changing the title of the SDL window seems to fix it for some reason.  Not really sure why.

**Comment by JayFoxRox** [comment] 2023-08-10 21:30
I'll close this as invalid:

- Issue is poorly named, and the problem is not described in a lot of detail.
    - There's no information about what development platform this happens on, what versions the LLVM toolchain was, what commands were ran to build the ISO, how the app was transferred to the Xbox etc.
- The blamed code and proposed solution are non-sensical, so it's likely not related to the code (certainly not the sample code in the repository), but something else.
- There are no steps to reproduce / no full repository or archive which can be downloaded to trigger this.
    - Not even a broken ISO has been shared.
- It's not clear how this was ran on the Xbox, or how the virtual XEMU Xbox had been set up.
    - Wether it works in XEMU also does not really matter, because it could always be emulation bugs.

I think the fact that doing random changes has an effect suggests that this is an issue with some conflicts of intermediate compilation results (or broken tooling altogether).
I speculate it's some C caching (ccache?) issue or some bug in extract-xiso; maybe also the way the image / app was transferred (FTP ASCII vs binary mode?).

It might also simply be incorrect use of the centralized Makefile (like swapping tool versions / flags, without forcing a full rebuild with `make -B`).

We can rename and re-open this (or open a new issue) if this turns out to be a valid report after all.

Closed.

**Closed by JayFoxRox** 2023-08-10 21:30 UTC
